# Generated by Django 3.1.2 on 2021-03-22 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzaapp', '0003_ordermodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermodel',
            name='status',
            field=models.CharField(default='Pending', max_length=10),
            preserve_default=False,
        ),
    ]
